### ISSUE TITLE
1.0.0-pre.1版本似乎有點問題

### ISSUE THREAD

**Issue by charleschiu2012** [JacobLinCool/Bahamut-Automation#32]
手動運行action之後出現如下error

Run JacobLinCool/Bahamut-Automation@action
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /Users/runner/work/_actions/JacobLinCool/Bahamut-Automation/action/action.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/runner/work/_actions/JacobLinCool/Bahamut-Automation/action/action.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) ***
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/runner/work/_actions/JacobLinCool/Bahamut-Automation/action/action.js'
  ]
***

**Comment by JacobLinCool** [comment]
@charleschiu2012 

感謝回報，問題已確認。

原因是因為 Dependencies 沒有一並複製到 Action branch。

正在修補中。

**Comment by JacobLinCool** [comment]
@charleschiu2012 

我發現此問題有點複雜，應該是基於 GitHub Action 跟 FireFox 之間的問題，但有個 workaround 是使用 webkit 作為瀏覽器。

像這樣：
```yaml
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@action
        with:
          modules: "report,ad_handler,login,sign,guild,answer,lottery,sayloud,builder,logout,report,telegram,discord,line_notify,issue"
          secrets: ${{ secrets.SECRETS }}
          browser: '{ "type": "webkit" }'
```

我在 Action 上測試過 Webkit 是可以用的， FireFox 則有 Google AD 跳出來時會有 Crash 問題，而 Chromium 一如往常不能播 mp4。

如果是 Local 執行 (使用 Bahamut Automation CLI)，則不會出現 FireFox 不能使用的問題。
