### ISSUE TITLE
Support YAML Config

### ISSUE THREAD

**Issue by JacobLinCool** [JacobLinCool/Bahamut-Automation#95]
YAML 比較易讀，也比較不會有忘記分號的問題。

預計新增支援 YAML 格式 Config。

**Comment by JacobLinCool** [comment]
目前預想的格式可能是這樣：

```yml
---
# 繼承設定自某個設定檔，可以內建的、路徑、或 URL
extends: recommended # 可能就先包含某些模組吧？

# 所有模組皆可存取的共用參數
shared:
    shared_key: shared_val

# 使用的模組及其參數，可以是內建的模組或是自製模組的路徑
modules:
    # 註冊一些通用函式
    report:
    ad_handler:

    # 主要功能模組
    login:
        username: string
        password: string
    sign:
    guild:
    answer:
    lottery:
        max_attempts: 20
    logout:

    # 以下是寄報告的部分
    telegram:
        channel: telegram_channel_id
    discord:
        webhook: discord_webhook_url
    line_notify:
        token: line_token
    issue:

    # 自製模組（範例）
    /path/to/module:
        param1: value1
        param2: value2

# 瀏覽器的設定
browser:
    type: firefox
    headless: true

```

看起來要大改模組取參數的標準了...
